# Generated by Django 6.0.7 on 2026-08-06 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("brands", "0002_rename_criated_by_brand_created_by"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="brand",
            options={
                "ordering": ["name"],
                "verbose_name": "marca",
                "verbose_name_plural": "marcas",
            },
        ),
    ]
