# Generated by Django 6.0.7 on 2026-07-29 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inflows", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="inflow",
            old_name="criated_by",
            new_name="created_by",
        ),
    ]
