# Generated by Django 6.0.7 on 2026-07-29 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("supliers", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="suplier",
            options={
                "ordering": ["name"],
                "verbose_name": "fornecedor",
                "verbose_name_plural": "fornecedores",
            },
        ),
    ]
