# Generated by Django 6.0.7 on 2026-07-29 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("supliers", "0002_alter_suplier_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="suplier",
            old_name="criated_by",
            new_name="created_by",
        ),
    ]
