# Generated by Django 6.0.7 on 2026-07-29 01:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("brands", "0001_initial"),
        ("categories", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="modificado em"),
                ),
                ("active", models.BooleanField(default=True, verbose_name="ativo")),
                ("title", models.CharField(max_length=200, verbose_name="título")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="descrição"),
                ),
                (
                    "serie_number",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="número de série",
                    ),
                ),
                (
                    "cost_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=20, verbose_name="preço de custo"
                    ),
                ),
                (
                    "selling_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=20, verbose_name="preço de venda"
                    ),
                ),
                ("quantity", models.IntegerField(default=0, verbose_name="quantidade")),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        related_query_name="product",
                        to="brands.brand",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        related_query_name="product",
                        to="categories.category",
                    ),
                ),
                (
                    "criated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="criado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "produto",
                "verbose_name_plural": "produtos",
                "ordering": ["title"],
            },
        ),
    ]
